# Generated by Django 2.1.7 on 2019-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='categories',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categorias',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
