# Generated by Django 2.1.7 on 2019-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190503_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categorias',
            field=models.ManyToManyField(help_text='Mantenha pressionado o "Control", ou "Command" no Mac, para selecionar mais de uma opção.', to='category.Category'),
        ),
    ]
